
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;


interface GameObjectInterface {
   //function createObject (string name, uint attack, uint defence, uint helth) external;
   //function createWarUnit (uint attack, uint defence) external;
   function takeDefence ( uint attack) external;

}
