
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "GameObject.sol";

contract Warrior is gameObject {
    
   constructor (uint attack_, uint defence_, uint helth_) public {
        tvm.accept();
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        objectAttack = attack_;
        objectDefence = defence_;
        objectHelth = helth_;

        
    } 

   modifier Alive {
		// Check that message was signed with contracts key.
		require(objectHelth > 0, 102);
		tvm.accept();
		_;
	}

    function rage () public Alive { 
        objectAttack += 1;
        callerAddress.transfer(10000, true, 1);
        tvm.accept();

    }
    

        
    

   
}
